const windowsTZArray = [
  'AUS Central Standard Time',
  'AUS Central Standard Time',
  'AUS Eastern Standard Time',
  'AUS Eastern Standard Time',
  'AUS Eastern Standard Time',
  'Afghanistan Standard Time',
  'Afghanistan Standard Time',
  'Alaskan Standard Time',
  'Alaskan Standard Time',
  'Alaskan Standard Time',
  'Alaskan Standard Time',
  'Alaskan Standard Time',
  'Alaskan Standard Time',
  'Alaskan Standard Time',
  'Aleutian Standard Time',
  'Aleutian Standard Time',
  'Altai Standard Time',
  'Altai Standard Time',
  'Arab Standard Time',
  'Arab Standard Time',
  'Arab Standard Time',
  'Arab Standard Time',
  'Arab Standard Time',
  'Arab Standard Time',
  'Arabian Standard Time',
  'Arabian Standard Time',
  'Arabian Standard Time',
  'Arabian Standard Time',
  'Arabic Standard Time',
  'Arabic Standard Time',
  'Argentina Standard Time',
  'Argentina Standard Time',
  'Argentina Standard Time',
  'Argentina Standard Time',
  'Argentina Standard Time',
  'Argentina Standard Time',
  'Argentina Standard Time',
  'Argentina Standard Time',
  'Argentina Standard Time',
  'Argentina Standard Time',
  'Argentina Standard Time',
  'Argentina Standard Time',
  'Argentina Standard Time',
  'Astrakhan Standard Time',
  'Astrakhan Standard Time',
  'Astrakhan Standard Time',
  'Atlantic Standard Time',
  'Atlantic Standard Time',
  'Atlantic Standard Time',
  'Atlantic Standard Time',
  'Atlantic Standard Time',
  'Atlantic Standard Time',
  'Atlantic Standard Time',
  'Aus Central W. Standard Time',
  'Aus Central W. Standard Time',
  'Azerbaijan Standard Time',
  'Azerbaijan Standard Time',
  'Azores Standard Time',
  'Azores Standard Time',
  'Azores Standard Time',
  'Bahia Standard Time',
  'Bahia Standard Time',
  'Bangladesh Standard Time',
  'Bangladesh Standard Time',
  'Bangladesh Standard Time',
  'Belarus Standard Time',
  'Belarus Standard Time',
  'Bougainville Standard Time',
  'Bougainville Standard Time',
  'Canada Central Standard Time',
  'Canada Central Standard Time',
  'Canada Central Standard Time',
  'Cape Verde Standard Time',
  'Cape Verde Standard Time',
  'Cape Verde Standard Time',
  'Caucasus Standard Time',
  'Caucasus Standard Time',
  'Cen. Australia Standard Time',
  'Cen. Australia Standard Time',
  'Cen. Australia Standard Time',
  'Central America Standard Time',
  'Central America Standard Time',
  'Central America Standard Time',
  'Central America Standard Time',
  'Central America Standard Time',
  'Central America Standard Time',
  'Central America Standard Time',
  'Central America Standard Time',
  'Central America Standard Time',
  'Central Asia Standard Time',
  'Central Asia Standard Time',
  'Central Asia Standard Time',
  'Central Asia Standard Time',
  'Central Asia Standard Time',
  'Central Asia Standard Time',
  'Central Asia Standard Time',
  'Central Asia Standard Time',
  'Central Brazilian Standard Time',
  'Central Brazilian Standard Time',
  'Central Brazilian Standard Time',
  'Central Europe Standard Time',
  'Central Europe Standard Time',
  'Central Europe Standard Time',
  'Central Europe Standard Time',
  'Central Europe Standard Time',
  'Central Europe Standard Time',
  'Central Europe Standard Time',
  'Central Europe Standard Time',
  'Central European Standard Time',
  'Central European Standard Time',
  'Central European Standard Time',
  'Central European Standard Time',
  'Central European Standard Time',
  'Central Pacific Standard Time',
  'Central Pacific Standard Time',
  'Central Pacific Standard Time',
  'Central Pacific Standard Time',
  'Central Pacific Standard Time',
  'Central Pacific Standard Time',
  'Central Pacific Standard Time',
  'Central Pacific Standard Time',
  'Central Standard Time',
  'Central Standard Time',
  'Central Standard Time',
  'Central Standard Time',
  'Central Standard Time',
  'Central Standard Time',
  'Central Standard Time',
  'Central Standard Time',
  'Central Standard Time',
  'Central Standard Time',
  'Central Standard Time',
  'Central Standard Time',
  'Central Standard Time',
  'Central Standard Time',
  'Central Standard Time (Mexico)',
  'Central Standard Time (Mexico)',
  'Central Standard Time (Mexico)',
  'Central Standard Time (Mexico)',
  'Central Standard Time (Mexico)',
  'Chatham Islands Standard Time',
  'Chatham Islands Standard Time',
  'China Standard Time',
  'China Standard Time',
  'China Standard Time',
  'China Standard Time',
  'Cuba Standard Time',
  'Cuba Standard Time',
  'Dateline Standard Time',
  'Dateline Standard Time',
  'E. Africa Standard Time',
  'E. Africa Standard Time',
  'E. Africa Standard Time',
  'E. Africa Standard Time',
  'E. Africa Standard Time',
  'E. Africa Standard Time',
  'E. Africa Standard Time',
  'E. Africa Standard Time',
  'E. Africa Standard Time',
  'E. Africa Standard Time',
  'E. Africa Standard Time',
  'E. Africa Standard Time',
  'E. Africa Standard Time',
  'E. Australia Standard Time',
  'E. Australia Standard Time',
  'E. Australia Standard Time',
  'E. Europe Standard Time',
  'E. Europe Standard Time',
  'E. South America Standard Time',
  'E. South America Standard Time',
  'Easter Island Standard Time',
  'Easter Island Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time',
  'Eastern Standard Time (Mexico)',
  'Eastern Standard Time (Mexico)',
  'Egypt Standard Time',
  'Egypt Standard Time',
  'Ekaterinburg Standard Time',
  'Ekaterinburg Standard Time',
  'FLE Standard Time',
  'FLE Standard Time',
  'FLE Standard Time',
  'FLE Standard Time',
  'FLE Standard Time',
  'FLE Standard Time',
  'FLE Standard Time',
  'FLE Standard Time',
  'FLE Standard Time',
  'FLE Standard Time',
  'Fiji Standard Time',
  'Fiji Standard Time',
  'GMT Standard Time',
  'GMT Standard Time',
  'GMT Standard Time',
  'GMT Standard Time',
  'GMT Standard Time',
  'GMT Standard Time',
  'GMT Standard Time',
  'GMT Standard Time',
  'GMT Standard Time',
  'GMT Standard Time',
  'GTB Standard Time',
  'GTB Standard Time',
  'GTB Standard Time',
  'GTB Standard Time',
  'GTB Standard Time',
  'Georgian Standard Time',
  'Georgian Standard Time',
  'Greenland Standard Time',
  'Greenland Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Greenwich Standard Time',
  'Haiti Standard Time',
  'Haiti Standard Time',
  'Hawaiian Standard Time',
  'Hawaiian Standard Time',
  'Hawaiian Standard Time',
  'Hawaiian Standard Time',
  'Hawaiian Standard Time',
  'Hawaiian Standard Time',
  'India Standard Time',
  'India Standard Time',
  'Iran Standard Time',
  'Iran Standard Time',
  'Israel Standard Time',
  'Israel Standard Time',
  'Jordan Standard Time',
  'Jordan Standard Time',
  'Kaliningrad Standard Time',
  'Kaliningrad Standard Time',
  'Korea Standard Time',
  'Korea Standard Time',
  'Libya Standard Time',
  'Libya Standard Time',
  'Line Islands Standard Time',
  'Line Islands Standard Time',
  'Line Islands Standard Time',
  'Lord Howe Standard Time',
  'Lord Howe Standard Time',
  'Magadan Standard Time',
  'Magadan Standard Time',
  'Magallanes Standard Time',
  'Magallanes Standard Time',
  'Marquesas Standard Time',
  'Marquesas Standard Time',
  'Mauritius Standard Time',
  'Mauritius Standard Time',
  'Mauritius Standard Time',
  'Mauritius Standard Time',
  'Middle East Standard Time',
  'Middle East Standard Time',
  'Montevideo Standard Time',
  'Montevideo Standard Time',
  'Morocco Standard Time',
  'Morocco Standard Time',
  'Morocco Standard Time',
  'Mountain Standard Time',
  'Mountain Standard Time',
  'Mountain Standard Time',
  'Mountain Standard Time',
  'Mountain Standard Time',
  'Mountain Standard Time',
  'Mountain Standard Time',
  'Mountain Standard Time',
  'Mountain Standard Time',
  'Mountain Standard Time (Mexico)',
  'Mountain Standard Time (Mexico)',
  'Mountain Standard Time (Mexico)',
  'Myanmar Standard Time',
  'Myanmar Standard Time',
  'Myanmar Standard Time',
  'N. Central Asia Standard Time',
  'N. Central Asia Standard Time',
  'Namibia Standard Time',
  'Namibia Standard Time',
  'Nepal Standard Time',
  'Nepal Standard Time',
  'New Zealand Standard Time',
  'New Zealand Standard Time',
  'New Zealand Standard Time',
  'Newfoundland Standard Time',
  'Newfoundland Standard Time',
  'Norfolk Standard Time',
  'Norfolk Standard Time',
  'North Asia East Standard Time',
  'North Asia East Standard Time',
  'North Asia Standard Time',
  'North Asia Standard Time',
  'North Asia Standard Time',
  'North Korea Standard Time',
  'North Korea Standard Time',
  'Omsk Standard Time',
  'Omsk Standard Time',
  'Pacific SA Standard Time',
  'Pacific SA Standard Time',
  'Pacific Standard Time',
  'Pacific Standard Time',
  'Pacific Standard Time',
  'Pacific Standard Time',
  'Pacific Standard Time (Mexico)',
  'Pacific Standard Time (Mexico)',
  'Pacific Standard Time (Mexico)',
  'Pakistan Standard Time',
  'Pakistan Standard Time',
  'Paraguay Standard Time',
  'Paraguay Standard Time',
  'Qyzylorda Standard Time',
  'Qyzylorda Standard Time',
  'Romance Standard Time',
  'Romance Standard Time',
  'Romance Standard Time',
  'Romance Standard Time',
  'Romance Standard Time',
  'Romance Standard Time',
  'Russia Time Zone 10',
  'Russia Time Zone 10',
  'Russia Time Zone 11',
  'Russia Time Zone 11',
  'Russia Time Zone 11',
  'Russia Time Zone 3',
  'Russia Time Zone 3',
  'Russian Standard Time',
  'Russian Standard Time',
  'Russian Standard Time',
  'Russian Standard Time',
  'SA Eastern Standard Time',
  'SA Eastern Standard Time',
  'SA Eastern Standard Time',
  'SA Eastern Standard Time',
  'SA Eastern Standard Time',
  'SA Eastern Standard Time',
  'SA Eastern Standard Time',
  'SA Eastern Standard Time',
  'SA Eastern Standard Time',
  'SA Eastern Standard Time',
  'SA Eastern Standard Time',
  'SA Eastern Standard Time',
  'SA Pacific Standard Time',
  'SA Pacific Standard Time',
  'SA Pacific Standard Time',
  'SA Pacific Standard Time',
  'SA Pacific Standard Time',
  'SA Pacific Standard Time',
  'SA Pacific Standard Time',
  'SA Pacific Standard Time',
  'SA Pacific Standard Time',
  'SA Pacific Standard Time',
  'SA Pacific Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SA Western Standard Time',
  'SE Asia Standard Time',
  'SE Asia Standard Time',
  'SE Asia Standard Time',
  'SE Asia Standard Time',
  'SE Asia Standard Time',
  'SE Asia Standard Time',
  'SE Asia Standard Time',
  'SE Asia Standard Time',
  'SE Asia Standard Time',
  'SE Asia Standard Time',
  'Saint Pierre Standard Time',
  'Saint Pierre Standard Time',
  'Sakhalin Standard Time',
  'Sakhalin Standard Time',
  'Samoa Standard Time',
  'Samoa Standard Time',
  'Sao Tome Standard Time',
  'Sao Tome Standard Time',
  'Saratov Standard Time',
  'Saratov Standard Time',
  'Singapore Standard Time',
  'Singapore Standard Time',
  'Singapore Standard Time',
  'Singapore Standard Time',
  'Singapore Standard Time',
  'Singapore Standard Time',
  'Singapore Standard Time',
  'Singapore Standard Time',
  'South Africa Standard Time',
  'South Africa Standard Time',
  'South Africa Standard Time',
  'South Africa Standard Time',
  'South Africa Standard Time',
  'South Africa Standard Time',
  'South Africa Standard Time',
  'South Africa Standard Time',
  'South Africa Standard Time',
  'South Africa Standard Time',
  'South Africa Standard Time',
  'South Africa Standard Time',
  'South Africa Standard Time',
  'South Sudan Standard Time',
  'South Sudan Standard Time',
  'Sri Lanka Standard Time',
  'Sri Lanka Standard Time',
  'Sudan Standard Time',
  'Sudan Standard Time',
  'Syria Standard Time',
  'Syria Standard Time',
  'Taipei Standard Time',
  'Taipei Standard Time',
  'Tasmania Standard Time',
  'Tasmania Standard Time',
  'Tasmania Standard Time',
  'Tasmania Standard Time',
  'Tocantins Standard Time',
  'Tocantins Standard Time',
  'Tokyo Standard Time',
  'Tokyo Standard Time',
  'Tokyo Standard Time',
  'Tokyo Standard Time',
  'Tokyo Standard Time',
  'Tokyo Standard Time',
  'Tomsk Standard Time',
  'Tomsk Standard Time',
  'Tonga Standard Time',
  'Tonga Standard Time',
  'Transbaikal Standard Time',
  'Transbaikal Standard Time',
  'Turkey Standard Time',
  'Turkey Standard Time',
  'Turks And Caicos Standard Time',
  'Turks And Caicos Standard Time',
  'US Eastern Standard Time',
  'US Eastern Standard Time',
  'US Eastern Standard Time',
  'US Eastern Standard Time',
  'US Mountain Standard Time',
  'US Mountain Standard Time',
  'US Mountain Standard Time',
  'US Mountain Standard Time',
  'US Mountain Standard Time',
  'US Mountain Standard Time',
  'US Mountain Standard Time',
  'UTC',
  'UTC',
  'UTC',
  'UTC+12',
  'UTC+12',
  'UTC+12',
  'UTC+12',
  'UTC+12',
  'UTC+12',
  'UTC+12',
  'UTC+12',
  'UTC+12',
  'UTC+13',
  'UTC+13',
  'UTC+13',
  'UTC+13',
  'UTC-02',
  'UTC-02',
  'UTC-02',
  'UTC-02',
  'UTC-08',
  'UTC-08',
  'UTC-08',
  'UTC-09',
  'UTC-09',
  'UTC-09',
  'UTC-11',
  'UTC-11',
  'UTC-11',
  'UTC-11',
  'UTC-11',
  'Ulaanbaatar Standard Time',
  'Ulaanbaatar Standard Time',
  'Ulaanbaatar Standard Time',
  'Venezuela Standard Time',
  'Venezuela Standard Time',
  'Vladivostok Standard Time',
  'Vladivostok Standard Time',
  'Vladivostok Standard Time',
  'Volgograd Standard Time',
  'Volgograd Standard Time',
  'W. Australia Standard Time',
  'W. Australia Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Central Africa Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Europe Standard Time',
  'W. Mongolia Standard Time',
  'W. Mongolia Standard Time',
  'West Asia Standard Time',
  'West Asia Standard Time',
  'West Asia Standard Time',
  'West Asia Standard Time',
  'West Asia Standard Time',
  'West Asia Standard Time',
  'West Asia Standard Time',
  'West Asia Standard Time',
  'West Asia Standard Time',
  'West Asia Standard Time',
  'West Asia Standard Time',
  'West Asia Standard Time',
  'West Asia Standard Time',
  'West Bank Standard Time',
  'West Bank Standard Time',
  'West Bank Standard Time',
  'West Pacific Standard Time',
  'West Pacific Standard Time',
  'West Pacific Standard Time',
  'West Pacific Standard Time',
  'West Pacific Standard Time',
  'West Pacific Standard Time',
  'West Pacific Standard Time',
  'Yakutsk Standard Time',
  'Yakutsk Standard Time',
  'Yakutsk Standard Time',
  'Yukon Standard Time',
  'Yukon Standard Time',
  'Yukon Standard Time',
];

const isoArray = [
  '001',
  'AU',
  '001',
  'AU',
  'AU',
  '001',
  'AF',
  '001',
  'US',
  'US',
  'US',
  'US',
  'US',
  'US',
  '001',
  'US',
  '001',
  'RU',
  '001',
  'BH',
  'KW',
  'QA',
  'SA',
  'YE',
  '001',
  'AE',
  'OM',
  'ZZ',
  '001',
  'IQ',
  '001',
  'AR',
  'AR',
  'AR',
  'AR',
  'AR',
  'AR',
  'AR',
  'AR',
  'AR',
  'AR',
  'AR',
  'AR',
  '001',
  'RU',
  'RU',
  '001',
  'BM',
  'CA',
  'CA',
  'CA',
  'CA',
  'GL',
  '001',
  'AU',
  '001',
  'AZ',
  '001',
  'GL',
  'PT',
  '001',
  'BR',
  '001',
  'BD',
  'BT',
  '001',
  'BY',
  '001',
  'PG',
  '001',
  'CA',
  'CA',
  '001',
  'CV',
  'ZZ',
  '001',
  'AM',
  '001',
  'AU',
  'AU',
  '001',
  'BZ',
  'CR',
  'EC',
  'GT',
  'HN',
  'NI',
  'SV',
  'ZZ',
  '001',
  'AQ',
  'CN',
  'IO',
  'KG',
  'KZ',
  'KZ',
  'ZZ',
  '001',
  'BR',
  'BR',
  '001',
  'AL',
  'CZ',
  'HU',
  'ME',
  'RS',
  'SI',
  'SK',
  '001',
  'BA',
  'HR',
  'MK',
  'PL',
  '001',
  'AQ',
  'FM',
  'FM',
  'NC',
  'SB',
  'VU',
  'ZZ',
  '001',
  'CA',
  'CA',
  'CA',
  'CA',
  'MX',
  'US',
  'US',
  'US',
  'US',
  'US',
  'US',
  'US',
  'ZZ',
  '001',
  'MX',
  'MX',
  'MX',
  'MX',
  '001',
  'NZ',
  '001',
  'CN',
  'HK',
  'MO',
  '001',
  'CU',
  '001',
  'ZZ',
  '001',
  'AQ',
  'DJ',
  'ER',
  'ET',
  'KE',
  'KM',
  'MG',
  'SO',
  'TZ',
  'UG',
  'YT',
  'ZZ',
  '001',
  'AU',
  'AU',
  '001',
  'MD',
  '001',
  'BR',
  '001',
  'CL',
  '001',
  'BS',
  'CA',
  'CA',
  'CA',
  'CA',
  'CA',
  'CA',
  'US',
  'US',
  'US',
  'US',
  'US',
  'US',
  'US',
  'ZZ',
  '001',
  'MX',
  '001',
  'EG',
  '001',
  'RU',
  '001',
  'AX',
  'BG',
  'EE',
  'FI',
  'LT',
  'LV',
  'UA',
  'UA',
  'UA',
  '001',
  'FJ',
  '001',
  'ES',
  'FO',
  'GB',
  'GG',
  'IE',
  'IM',
  'JE',
  'PT',
  'PT',
  '001',
  'CY',
  'CY',
  'GR',
  'RO',
  '001',
  'GE',
  '001',
  'GL',
  '001',
  'BF',
  'CI',
  'GH',
  'GL',
  'GM',
  'GN',
  'GW',
  'IS',
  'LR',
  'ML',
  'MR',
  'SH',
  'SL',
  'SN',
  'TG',
  '001',
  'HT',
  '001',
  'CK',
  'PF',
  'UM',
  'US',
  'ZZ',
  '001',
  'IN',
  '001',
  'IR',
  '001',
  'IL',
  '001',
  'JO',
  '001',
  'RU',
  '001',
  'KR',
  '001',
  'LY',
  '001',
  'KI',
  'ZZ',
  '001',
  'AU',
  '001',
  'RU',
  '001',
  'CL',
  '001',
  'PF',
  '001',
  'MU',
  'RE',
  'SC',
  '001',
  'LB',
  '001',
  'UY',
  '001',
  'EH',
  'MA',
  '001',
  'CA',
  'CA',
  'CA',
  'CA',
  'MX',
  'US',
  'US',
  'ZZ',
  '001',
  'MX',
  'MX',
  '001',
  'CC',
  'MM',
  '001',
  'RU',
  '001',
  'NA',
  '001',
  'NP',
  '001',
  'AQ',
  'NZ',
  '001',
  'CA',
  '001',
  'NF',
  '001',
  'RU',
  '001',
  'RU',
  'RU',
  '001',
  'KP',
  '001',
  'RU',
  '001',
  'CL',
  '001',
  'CA',
  'US',
  'ZZ',
  '001',
  'MX',
  'MX',
  '001',
  'PK',
  '001',
  'PY',
  '001',
  'KZ',
  '001',
  'BE',
  'DK',
  'ES',
  'ES',
  'FR',
  '001',
  'RU',
  '001',
  'RU',
  'RU',
  '001',
  'RU',
  '001',
  'RU',
  'RU',
  'UA',
  '001',
  'AQ',
  'AQ',
  'BR',
  'BR',
  'BR',
  'BR',
  'BR',
  'FK',
  'GF',
  'SR',
  'ZZ',
  '001',
  'BR',
  'BR',
  'CA',
  'CO',
  'EC',
  'JM',
  'KY',
  'PA',
  'PE',
  'ZZ',
  '001',
  'AG',
  'AI',
  'AW',
  'BB',
  'BL',
  'BO',
  'BQ',
  'BR',
  'BR',
  'BR',
  'CA',
  'CW',
  'DM',
  'DO',
  'GD',
  'GP',
  'GY',
  'KN',
  'LC',
  'MF',
  'MQ',
  'MS',
  'PR',
  'SX',
  'TT',
  'VC',
  'VG',
  'VI',
  'ZZ',
  '001',
  'AQ',
  'CX',
  'ID',
  'ID',
  'KH',
  'LA',
  'TH',
  'VN',
  'ZZ',
  '001',
  'PM',
  '001',
  'RU',
  '001',
  'WS',
  '001',
  'ST',
  '001',
  'RU',
  '001',
  'BN',
  'ID',
  'MY',
  'MY',
  'PH',
  'SG',
  'ZZ',
  '001',
  'BI',
  'BW',
  'CD',
  'LS',
  'MW',
  'MZ',
  'RW',
  'SZ',
  'ZA',
  'ZM',
  'ZW',
  'ZZ',
  '001',
  'SS',
  '001',
  'LK',
  '001',
  'SD',
  '001',
  'SY',
  '001',
  'TW',
  '001',
  'AU',
  'AU',
  'AU',
  '001',
  'BR',
  '001',
  'ID',
  'JP',
  'PW',
  'TL',
  'ZZ',
  '001',
  'RU',
  '001',
  'TO',
  '001',
  'RU',
  '001',
  'TR',
  '001',
  'TC',
  '001',
  'US',
  'US',
  'US',
  '001',
  'CA',
  'CA',
  'CA',
  'MX',
  'US',
  'ZZ',
  '001',
  'ZZ',
  'ZZ',
  '001',
  'KI',
  'MH',
  'MH',
  'NR',
  'TV',
  'UM',
  'WF',
  'ZZ',
  '001',
  'KI',
  'TK',
  'ZZ',
  '001',
  'BR',
  'GS',
  'ZZ',
  '001',
  'PN',
  'ZZ',
  '001',
  'PF',
  'ZZ',
  '001',
  'AS',
  'NU',
  'UM',
  'ZZ',
  '001',
  'MN',
  'MN',
  '001',
  'VE',
  '001',
  'RU',
  'RU',
  '001',
  'RU',
  '001',
  'AU',
  '001',
  'AO',
  'BJ',
  'CD',
  'CF',
  'CG',
  'CM',
  'DZ',
  'GA',
  'GQ',
  'NE',
  'NG',
  'TD',
  'TN',
  'ZZ',
  '001',
  'AD',
  'AT',
  'CH',
  'DE',
  'DE',
  'GI',
  'IT',
  'LI',
  'LU',
  'MC',
  'MT',
  'NL',
  'NO',
  'SE',
  'SJ',
  'SM',
  'VA',
  '001',
  'MN',
  '001',
  'AQ',
  'KZ',
  'KZ',
  'KZ',
  'KZ',
  'MV',
  'TF',
  'TJ',
  'TM',
  'UZ',
  'UZ',
  'ZZ',
  '001',
  'PS',
  'PS',
  '001',
  'AQ',
  'FM',
  'GU',
  'MP',
  'PG',
  'ZZ',
  '001',
  'RU',
  'RU',
  '001',
  'CA',
  'CA',
];

const unixTZArray = [
  'Australia/Darwin',
  'Australia/Darwin',
  'Australia/Sydney',
  'Australia/Sydney',
  'Australia/Melbourne',
  'Asia/Kabul',
  'Asia/Kabul',
  'America/Anchorage',
  'America/Anchorage',
  'America/Juneau',
  'America/Metlakatla',
  'America/Nome',
  'America/Sitka',
  'America/Yakutat',
  'America/Adak',
  'America/Adak',
  'Asia/Barnaul',
  'Asia/Barnaul',
  'Asia/Riyadh',
  'Asia/Bahrain',
  'Asia/Kuwait',
  'Asia/Qatar',
  'Asia/Riyadh',
  'Asia/Aden',
  'Asia/Dubai',
  'Asia/Dubai',
  'Asia/Muscat',
  'Etc/GMT-4',
  'Asia/Baghdad',
  'Asia/Baghdad',
  'America/Buenos_Aires',
  'America/Buenos_Aires',
  'America/Argentina/La_Rioja',
  'America/Argentina/Rio_Gallegos',
  'America/Argentina/Salta',
  'America/Argentina/San_Juan',
  'America/Argentina/San_Luis',
  'America/Argentina/Tucuman',
  'America/Argentina/Ushuaia',
  'America/Catamarca',
  'America/Cordoba',
  'America/Jujuy',
  'America/Mendoza',
  'Europe/Astrakhan',
  'Europe/Astrakhan',
  'Europe/Ulyanovsk',
  'America/Halifax',
  'Atlantic/Bermuda',
  'America/Halifax',
  'America/Glace_Bay',
  'America/Goose_Bay',
  'America/Moncton',
  'America/Thule',
  'Australia/Eucla',
  'Australia/Eucla',
  'Asia/Baku',
  'Asia/Baku',
  'Atlantic/Azores',
  'America/Scoresbysund',
  'Atlantic/Azores',
  'America/Bahia',
  'America/Bahia',
  'Asia/Dhaka',
  'Asia/Dhaka',
  'Asia/Thimphu',
  'Europe/Minsk',
  'Europe/Minsk',
  'Pacific/Bougainville',
  'Pacific/Bougainville',
  'America/Regina',
  'America/Regina',
  'America/Swift_Current',
  'Atlantic/Cape_Verde',
  'Atlantic/Cape_Verde',
  'Etc/GMT+1',
  'Asia/Yerevan',
  'Asia/Yerevan',
  'Australia/Adelaide',
  'Australia/Adelaide',
  'Australia/Broken_Hill',
  'America/Guatemala',
  'America/Belize',
  'America/Costa_Rica',
  'Pacific/Galapagos',
  'America/Guatemala',
  'America/Tegucigalpa',
  'America/Managua',
  'America/El_Salvador',
  'Etc/GMT+6',
  'Asia/Almaty',
  'Antarctica/Vostok',
  'Asia/Urumqi',
  'Indian/Chagos',
  'Asia/Bishkek',
  'Asia/Almaty',
  'Asia/Qostanay',
  'Etc/GMT-6',
  'America/Cuiaba',
  'America/Cuiaba',
  'America/Campo_Grande',
  'Europe/Budapest',
  'Europe/Tirane',
  'Europe/Prague',
  'Europe/Budapest',
  'Europe/Podgorica',
  'Europe/Belgrade',
  'Europe/Ljubljana',
  'Europe/Bratislava',
  'Europe/Warsaw',
  'Europe/Sarajevo',
  'Europe/Zagreb',
  'Europe/Skopje',
  'Europe/Warsaw',
  'Pacific/Guadalcanal',
  'Antarctica/Casey',
  'Pacific/Ponape',
  'Pacific/Kosrae',
  'Pacific/Noumea',
  'Pacific/Guadalcanal',
  'Pacific/Efate',
  'Etc/GMT-11',
  'America/Chicago',
  'America/Winnipeg',
  'America/Rainy_River',
  'America/Rankin_Inlet',
  'America/Resolute',
  'America/Matamoros',
  'America/Chicago',
  'America/Indiana/Knox',
  'America/Indiana/Tell_City',
  'America/Menominee',
  'America/North_Dakota/Beulah',
  'America/North_Dakota/Center',
  'America/North_Dakota/New_Salem',
  'CST6CDT',
  'America/Mexico_City',
  'America/Mexico_City',
  'America/Bahia_Banderas',
  'America/Merida',
  'America/Monterrey',
  'Pacific/Chatham',
  'Pacific/Chatham',
  'Asia/Shanghai',
  'Asia/Shanghai',
  'Asia/Hong_Kong',
  'Asia/Macau',
  'America/Havana',
  'America/Havana',
  'Etc/GMT+12',
  'Etc/GMT+12',
  'Africa/Nairobi',
  'Antarctica/Syowa',
  'Africa/Djibouti',
  'Africa/Asmera',
  'Africa/Addis_Ababa',
  'Africa/Nairobi',
  'Indian/Comoro',
  'Indian/Antananarivo',
  'Africa/Mogadishu',
  'Africa/Dar_es_Salaam',
  'Africa/Kampala',
  'Indian/Mayotte',
  'Etc/GMT-3',
  'Australia/Brisbane',
  'Australia/Brisbane',
  'Australia/Lindeman',
  'Europe/Chisinau',
  'Europe/Chisinau',
  'America/Sao_Paulo',
  'America/Sao_Paulo',
  'Pacific/Easter',
  'Pacific/Easter',
  'America/New_York',
  'America/Nassau',
  'America/Toronto',
  'America/Iqaluit',
  'America/Montreal',
  'America/Nipigon',
  'America/Pangnirtung',
  'America/Thunder_Bay',
  'America/New_York',
  'America/Detroit',
  'America/Indiana/Petersburg',
  'America/Indiana/Vincennes',
  'America/Indiana/Winamac',
  'America/Kentucky/Monticello',
  'America/Louisville',
  'EST5EDT',
  'America/Cancun',
  'America/Cancun',
  'Africa/Cairo',
  'Africa/Cairo',
  'Asia/Yekaterinburg',
  'Asia/Yekaterinburg',
  'Europe/Kiev',
  'Europe/Mariehamn',
  'Europe/Sofia',
  'Europe/Tallinn',
  'Europe/Helsinki',
  'Europe/Vilnius',
  'Europe/Riga',
  'Europe/Kiev',
  'Europe/Uzhgorod',
  'Europe/Zaporozhye',
  'Pacific/Fiji',
  'Pacific/Fiji',
  'Europe/London',
  'Atlantic/Canary',
  'Atlantic/Faeroe',
  'Europe/London',
  'Europe/Guernsey',
  'Europe/Dublin',
  'Europe/Isle_of_Man',
  'Europe/Jersey',
  'Europe/Lisbon',
  'Atlantic/Madeira',
  'Europe/Bucharest',
  'Asia/Nicosia',
  'Asia/Famagusta',
  'Europe/Athens',
  'Europe/Bucharest',
  'Asia/Tbilisi',
  'Asia/Tbilisi',
  'America/Godthab',
  'America/Godthab',
  'Atlantic/Reykjavik',
  'Africa/Ouagadougou',
  'Africa/Abidjan',
  'Africa/Accra',
  'America/Danmarkshavn',
  'Africa/Banjul',
  'Africa/Conakry',
  'Africa/Bissau',
  'Atlantic/Reykjavik',
  'Africa/Monrovia',
  'Africa/Bamako',
  'Africa/Nouakchott',
  'Atlantic/St_Helena',
  'Africa/Freetown',
  'Africa/Dakar',
  'Africa/Lome',
  'America/Port-au-Prince',
  'America/Port-au-Prince',
  'Pacific/Honolulu',
  'Pacific/Rarotonga',
  'Pacific/Tahiti',
  'Pacific/Johnston',
  'Pacific/Honolulu',
  'Etc/GMT+10',
  'Asia/Calcutta',
  'Asia/Calcutta',
  'Asia/Tehran',
  'Asia/Tehran',
  'Asia/Jerusalem',
  'Asia/Jerusalem',
  'Asia/Amman',
  'Asia/Amman',
  'Europe/Kaliningrad',
  'Europe/Kaliningrad',
  'Asia/Seoul',
  'Asia/Seoul',
  'Africa/Tripoli',
  'Africa/Tripoli',
  'Pacific/Kiritimati',
  'Pacific/Kiritimati',
  'Etc/GMT-14',
  'Australia/Lord_Howe',
  'Australia/Lord_Howe',
  'Asia/Magadan',
  'Asia/Magadan',
  'America/Punta_Arenas',
  'America/Punta_Arenas',
  'Pacific/Marquesas',
  'Pacific/Marquesas',
  'Indian/Mauritius',
  'Indian/Mauritius',
  'Indian/Reunion',
  'Indian/Mahe',
  'Asia/Beirut',
  'Asia/Beirut',
  'America/Montevideo',
  'America/Montevideo',
  'Africa/Casablanca',
  'Africa/El_Aaiun',
  'Africa/Casablanca',
  'America/Denver',
  'America/Edmonton',
  'America/Cambridge_Bay',
  'America/Inuvik',
  'America/Yellowknife',
  'America/Ojinaga',
  'America/Denver',
  'America/Boise',
  'MST7MDT',
  'America/Chihuahua',
  'America/Chihuahua',
  'America/Mazatlan',
  'Asia/Rangoon',
  'Indian/Cocos',
  'Asia/Rangoon',
  'Asia/Novosibirsk',
  'Asia/Novosibirsk',
  'Africa/Windhoek',
  'Africa/Windhoek',
  'Asia/Katmandu',
  'Asia/Katmandu',
  'Pacific/Auckland',
  'Antarctica/McMurdo',
  'Pacific/Auckland',
  'America/St_Johns',
  'America/St_Johns',
  'Pacific/Norfolk',
  'Pacific/Norfolk',
  'Asia/Irkutsk',
  'Asia/Irkutsk',
  'Asia/Krasnoyarsk',
  'Asia/Krasnoyarsk',
  'Asia/Novokuznetsk',
  'Asia/Pyongyang',
  'Asia/Pyongyang',
  'Asia/Omsk',
  'Asia/Omsk',
  'America/Santiago',
  'America/Santiago',
  'America/Los_Angeles',
  'America/Vancouver',
  'America/Los_Angeles',
  'PST8PDT',
  'America/Tijuana',
  'America/Tijuana',
  'America/Santa_Isabel',
  'Asia/Karachi',
  'Asia/Karachi',
  'America/Asuncion',
  'America/Asuncion',
  'Asia/Qyzylorda',
  'Asia/Qyzylorda',
  'Europe/Paris',
  'Europe/Brussels',
  'Europe/Copenhagen',
  'Europe/Madrid',
  'Africa/Ceuta',
  'Europe/Paris',
  'Asia/Srednekolymsk',
  'Asia/Srednekolymsk',
  'Asia/Kamchatka',
  'Asia/Kamchatka',
  'Asia/Anadyr',
  'Europe/Samara',
  'Europe/Samara',
  'Europe/Moscow',
  'Europe/Moscow',
  'Europe/Kirov',
  'Europe/Simferopol',
  'America/Cayenne',
  'Antarctica/Rothera',
  'Antarctica/Palmer',
  'America/Fortaleza',
  'America/Belem',
  'America/Maceio',
  'America/Recife',
  'America/Santarem',
  'Atlantic/Stanley',
  'America/Cayenne',
  'America/Paramaribo',
  'Etc/GMT+3',
  'America/Bogota',
  'America/Rio_Branco',
  'America/Eirunepe',
  'America/Coral_Harbour',
  'America/Bogota',
  'America/Guayaquil',
  'America/Jamaica',
  'America/Cayman',
  'America/Panama',
  'America/Lima',
  'Etc/GMT+5',
  'America/La_Paz',
  'America/Antigua',
  'America/Anguilla',
  'America/Aruba',
  'America/Barbados',
  'America/St_Barthelemy',
  'America/La_Paz',
  'America/Kralendijk',
  'America/Manaus',
  'America/Boa_Vista',
  'America/Porto_Velho',
  'America/Blanc-Sablon',
  'America/Curacao',
  'America/Dominica',
  'America/Santo_Domingo',
  'America/Grenada',
  'America/Guadeloupe',
  'America/Guyana',
  'America/St_Kitts',
  'America/St_Lucia',
  'America/Marigot',
  'America/Martinique',
  'America/Montserrat',
  'America/Puerto_Rico',
  'America/Lower_Princes',
  'America/Port_of_Spain',
  'America/St_Vincent',
  'America/Tortola',
  'America/St_Thomas',
  'Etc/GMT+4',
  'Asia/Bangkok',
  'Antarctica/Davis',
  'Indian/Christmas',
  'Asia/Jakarta',
  'Asia/Pontianak',
  'Asia/Phnom_Penh',
  'Asia/Vientiane',
  'Asia/Bangkok',
  'Asia/Saigon',
  'Etc/GMT-7',
  'America/Miquelon',
  'America/Miquelon',
  'Asia/Sakhalin',
  'Asia/Sakhalin',
  'Pacific/Apia',
  'Pacific/Apia',
  'Africa/Sao_Tome',
  'Africa/Sao_Tome',
  'Europe/Saratov',
  'Europe/Saratov',
  'Asia/Singapore',
  'Asia/Brunei',
  'Asia/Makassar',
  'Asia/Kuala_Lumpur',
  'Asia/Kuching',
  'Asia/Manila',
  'Asia/Singapore',
  'Etc/GMT-8',
  'Africa/Johannesburg',
  'Africa/Bujumbura',
  'Africa/Gaborone',
  'Africa/Lubumbashi',
  'Africa/Maseru',
  'Africa/Blantyre',
  'Africa/Maputo',
  'Africa/Kigali',
  'Africa/Mbabane',
  'Africa/Johannesburg',
  'Africa/Lusaka',
  'Africa/Harare',
  'Etc/GMT-2',
  'Africa/Juba',
  'Africa/Juba',
  'Asia/Colombo',
  'Asia/Colombo',
  'Africa/Khartoum',
  'Africa/Khartoum',
  'Asia/Damascus',
  'Asia/Damascus',
  'Asia/Taipei',
  'Asia/Taipei',
  'Australia/Hobart',
  'Australia/Hobart',
  'Australia/Currie',
  'Antarctica/Macquarie',
  'America/Araguaina',
  'America/Araguaina',
  'Asia/Tokyo',
  'Asia/Jayapura',
  'Asia/Tokyo',
  'Pacific/Palau',
  'Asia/Dili',
  'Etc/GMT-9',
  'Asia/Tomsk',
  'Asia/Tomsk',
  'Pacific/Tongatapu',
  'Pacific/Tongatapu',
  'Asia/Chita',
  'Asia/Chita',
  'Europe/Istanbul',
  'Europe/Istanbul',
  'America/Grand_Turk',
  'America/Grand_Turk',
  'America/Indianapolis',
  'America/Indianapolis',
  'America/Indiana/Marengo',
  'America/Indiana/Vevay',
  'America/Phoenix',
  'America/Creston',
  'America/Dawson_Creek',
  'America/Fort_Nelson',
  'America/Hermosillo',
  'America/Phoenix',
  'Etc/GMT+7',
  'Etc/UTC',
  'Etc/UTC',
  'Etc/GMT',
  'Etc/GMT-12',
  'Pacific/Tarawa',
  'Pacific/Majuro',
  'Pacific/Kwajalein',
  'Pacific/Nauru',
  'Pacific/Funafuti',
  'Pacific/Wake',
  'Pacific/Wallis',
  'Etc/GMT-12',
  'Etc/GMT-13',
  'Pacific/Enderbury',
  'Pacific/Fakaofo',
  'Etc/GMT-13',
  'Etc/GMT+2',
  'America/Noronha',
  'Atlantic/South_Georgia',
  'Etc/GMT+2',
  'Etc/GMT+8',
  'Pacific/Pitcairn',
  'Etc/GMT+8',
  'Etc/GMT+9',
  'Pacific/Gambier',
  'Etc/GMT+9',
  'Etc/GMT+11',
  'Pacific/Pago_Pago',
  'Pacific/Niue',
  'Pacific/Midway',
  'Etc/GMT+11',
  'Asia/Ulaanbaatar',
  'Asia/Ulaanbaatar',
  'Asia/Choibalsan',
  'America/Caracas',
  'America/Caracas',
  'Asia/Vladivostok',
  'Asia/Vladivostok',
  'Asia/Ust-Nera',
  'Europe/Volgograd',
  'Europe/Volgograd',
  'Australia/Perth',
  'Australia/Perth',
  'Africa/Lagos',
  'Africa/Luanda',
  'Africa/Porto-Novo',
  'Africa/Kinshasa',
  'Africa/Bangui',
  'Africa/Brazzaville',
  'Africa/Douala',
  'Africa/Algiers',
  'Africa/Libreville',
  'Africa/Malabo',
  'Africa/Niamey',
  'Africa/Lagos',
  'Africa/Ndjamena',
  'Africa/Tunis',
  'Etc/GMT-1',
  'Europe/Berlin',
  'Europe/Andorra',
  'Europe/Vienna',
  'Europe/Zurich',
  'Europe/Berlin',
  'Europe/Busingen',
  'Europe/Gibraltar',
  'Europe/Rome',
  'Europe/Vaduz',
  'Europe/Luxembourg',
  'Europe/Monaco',
  'Europe/Malta',
  'Europe/Amsterdam',
  'Europe/Oslo',
  'Europe/Stockholm',
  'Arctic/Longyearbyen',
  'Europe/San_Marino',
  'Europe/Vatican',
  'Asia/Hovd',
  'Asia/Hovd',
  'Asia/Tashkent',
  'Antarctica/Mawson',
  'Asia/Oral',
  'Asia/Aqtau',
  'Asia/Aqtobe',
  'Asia/Atyrau',
  'Indian/Maldives',
  'Indian/Kerguelen',
  'Asia/Dushanbe',
  'Asia/Ashgabat',
  'Asia/Tashkent',
  'Asia/Samarkand',
  'Etc/GMT-5',
  'Asia/Hebron',
  'Asia/Hebron',
  'Asia/Gaza',
  'Pacific/Port_Moresby',
  'Antarctica/DumontDUrville',
  'Pacific/Truk',
  'Pacific/Guam',
  'Pacific/Saipan',
  'Pacific/Port_Moresby',
  'Etc/GMT-10',
  'Asia/Yakutsk',
  'Asia/Yakutsk',
  'Asia/Khandyga',
  'America/Whitehorse',
  'America/Whitehorse',
  'America/Dawson',
];

export function toUnix(code: string) {
  if (unixTZArray.indexOf(code) > -1) return code;

  const inWinIso = windowsTZArray.indexOf(code);
  if (inWinIso > -1) {
    return unixTZArray[inWinIso];
  }

  const inIso = isoArray.indexOf(code);
  if (inIso > -1) {
    return unixTZArray[inIso];
  }
}

export function toWindows(code: string) {
  if (windowsTZArray.indexOf(code) > -1) return code;

  const inWinIso = unixTZArray.indexOf(code);
  if (inWinIso > -1) {
    return windowsTZArray[inWinIso];
  }

  const inIso = isoArray.indexOf(code);
  if (inIso > -1) {
    return windowsTZArray[inIso];
  }
}
